### ISSUE TITLE
How accurate is this? Is it based on other languages primer tm calculators?

### ISSUE THREAD

**Issue by tnrich** [dohalloran/primertmcalc#1]
Hey there,

First off, thanks for making this public package! I think it is great that javascript is starting to get some open source bio util functions. 

I was just wondering if you could provide more info about the algorithm being employed by the package as well as perhaps a comparison to other already standard tm calculators like from bio perl/python packages.

Thanks again :)

**Comment by dohalloran** [comment]
Hi! 

thanks for your interest in primertmcalc - the algorithm implements the formula described by Rychlik et al 1990 (PMCID: PMC332522), and also Li et al. 2008 (PMCID: PMC2396641). 

I have tested a Perl version against Primer3's algorithm and they perform similarly (see Fig 2B - PMID: 26052342). 

I also saw your pull request - I will review and merge - great ideas - thanks!
